language: node_js
node_js:
- 9
sudo: required
env:
- DOCKER_COMPOSE_VERSION=1.17.1
services:
- docker
before_install:
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- npm install
- npx poi build
- docker build -t vatusa/ssdock .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u "$DOCKER_USERNAME" -p
  "$DOCKER_PASSWORD"; docker push vatusa/frontend; fi
